Repository zikula/core, pull requests merged in 2020-02, with the labels that each got.

#4125 Extension installer refactor
  CHANGELOG-3.0.md
  src/Zikula/CoreBundle/Resources/config/services.yaml
  src/Zikula/CoreInstallerBundle/Helper/BlockHelper.php
  src/Zikula/CoreInstallerBundle/Helper/CoreInstallerExtensionHelper.php
  src/Zikula/CoreInstallerBundle/Stage/Install/CompleteStage.php
  src/system/BlocksModule/BlocksModuleInstaller.php
  src/system/CategoriesModule/CategoriesModuleInstaller.php
  src/system/CategoriesModule/Resources/config/services.yaml
  src/system/ExtensionsModule/Collector/InstallerCollector.php
  src/system/ExtensionsModule/DependencyInjection/ZikulaExtensionsExtension.php
  src/system/ExtensionsModule/ExtensionVariablesTrait.php
  src/system/ExtensionsModule/ExtensionsModuleInstaller.php
  src/system/ExtensionsModule/Helper/ExtensionHelper.php
  src/system/ExtensionsModule/Installer/AbstractExtensionInstaller.php
  src/system/ExtensionsModule/Installer/ExtensionInstallerInterface.php
  src/system/ExtensionsModule/Resources/config/services.yaml
  src/system/GroupsModule/GroupsModuleInstaller.php
  src/system/MailerModule/MailerModuleInstaller.php
  src/system/PermissionsModule/PermissionsModuleInstaller.php
  src/system/SecurityCenterModule/Resources/config/services.yaml
  src/system/SecurityCenterModule/SecurityCenterModuleInstaller.php
  src/system/SettingsModule/Resources/config/services.yaml
  src/system/SettingsModule/SettingsModuleInstaller.php
  src/system/UsersModule/Resources/config/services.yaml
  src/system/UsersModule/UsersModuleInstaller.php
Labels: BC Break

#4135 improve password handling
  CHANGELOG-3.0.md
  config/packages/security.yaml
  src/Zikula/CoreInstallerBundle/Helper/StageHelper.php
  src/Zikula/CoreInstallerBundle/Helper/SuperUserHelper.php
  src/Zikula/CoreInstallerBundle/Stage/Install/AjaxInstallerStage.php
  src/Zikula/CoreInstallerBundle/Validator/Constraints/AuthenticateAdminLoginValidator.php
  src/system/UsersModule/Entity/Repository/UserRepository.php
  src/system/UsersModule/UsersModuleInstaller.php
  src/system/ZAuthModule/Api/ApiInterface/PasswordApiInterface.php
  src/system/ZAuthModule/Api/PasswordApi.php
  src/system/ZAuthModule/AuthenticationMethod/AbstractNativeAuthenticationMethod.php
  src/system/ZAuthModule/Controller/AccountController.php
  src/system/ZAuthModule/Controller/RegistrationController.php
  src/system/ZAuthModule/Controller/UserAdministrationController.php
  src/system/ZAuthModule/Entity/AuthenticationMappingEntity.php
  src/system/ZAuthModule/Entity/Repository/AuthenticationMappingRepository.php
  src/system/ZAuthModule/Entity/RepositoryInterface/AuthenticationMappingRepositoryInterface.php
  src/system/ZAuthModule/Form/Type/AdminCreatedUserType.php
  src/system/ZAuthModule/Form/Type/AdminModifyUserType.php
  src/system/ZAuthModule/Form/Type/BatchForcePasswordChangeType.php
  src/system/ZAuthModule/Form/Type/ChangePasswordType.php
  src/system/ZAuthModule/Form/Type/ConfigType.php
  src/system/ZAuthModule/Form/Type/RegistrationType.php
  src/system/ZAuthModule/Form/Type/VerifyRegistrationType.php
  src/system/ZAuthModule/Helper/FileIOHelper.php
  src/system/ZAuthModule/Helper/LostPasswordVerificationHelper.php
  src/system/ZAuthModule/Helper/RegistrationVerificationHelper.php
  src/system/ZAuthModule/Menu/ExtensionMenu.php
  src/system/ZAuthModule/Resources/public/js/README.md
  src/system/ZAuthModule/Resources/public/js/Zikula.ZAuth.PWStrength.Init.js
  src/system/ZAuthModule/Resources/public/js/Zikula.ZAuth.PassMeter.js
  src/system/ZAuthModule/Resources/public/js/Zikula.ZAuth.PasswordGenerator.js
  src/system/ZAuthModule/Resources/public/js/pwstrength-bootstrap.js
  src/system/ZAuthModule/Resources/public/js/pwstrength-bootstrap.min.js
  src/system/ZAuthModule/Resources/public/js/pwstrength-bootstrap.min.map
  src/system/ZAuthModule/Resources/views/Account/changePassword.html.twig
  src/system/ZAuthModule/Resources/views/Authentication/PasswordGenerator.html.twig
  src/system/ZAuthModule/Resources/views/Authentication/register.html.twig
  src/system/ZAuthModule/Resources/views/Config/config.html.twig
  src/system/ZAuthModule/Resources/views/Registration/verify.html.twig
  src/system/ZAuthModule/Resources/views/UserAdministration/batchForcePasswordChange.html.twig
  src/system/ZAuthModule/Resources/views/UserAdministration/create.html.twig
  src/system/ZAuthModule/Resources/views/UserAdministration/modify.html.twig
  src/system/ZAuthModule/Tests/Api/PasswordApiTest.php
  src/system/ZAuthModule/Validator/Constraints/ValidPasswordChangeValidator.php
  src/system/ZAuthModule/Validator/Constraints/ValidPasswordValidator.php
  src/system/ZAuthModule/Validator/Constraints/ValidRegistrationVerificationValidator.php
  src/system/ZAuthModule/ZAuthConstant.php
  src/system/ZAuthModule/ZAuthModuleInstaller.php
  src/system/ZAuthModule/composer.json
Labels: BC Break, Feature

#4143 Add PermissionCheck Annotation
  CHANGELOG-3.0.md
  docs/AccessControl/Permissions/Dev/PermissionCheckAnnotation.md
  src/system/GroupsModule/Controller/GroupController.php
  src/system/PermissionsModule/Annotation/PermissionCheck.php
  src/system/PermissionsModule/Listener/ControllerPermissionCheckAnnotationReaderListener.php
  src/system/PermissionsModule/Tests/Api/AbstractPermissionTestCase.php
  src/system/PermissionsModule/Tests/Api/CheckPermissionAnnotationTest.php
  src/system/PermissionsModule/Tests/Api/Fixtures/BarController.php
  src/system/PermissionsModule/Tests/Api/Fixtures/FailController.php
  src/system/PermissionsModule/Tests/Api/Fixtures/FooController.php
  src/system/PermissionsModule/Tests/Api/PermissionApiTest.php
  src/system/SettingsModule/Controller/SettingsController.php
  src/system/ThemeModule/Controller/ConfigController.php
Labels: Feature

#4146 added docs about permissions and categories
  docs/AccessControl/Permissions/Dev/Implementation.md
  docs/AccessControl/Permissions/Elements.md
  docs/AccessControl/Permissions/IndividualRules.md
  docs/AccessControl/Permissions/Management.md
  docs/AccessControl/Permissions/README.md
  docs/AccessControl/Permissions/RegularExpressions.md
  docs/Integration/Categories/README.md
  src/system/PermissionsModule/Api/PermissionApi.php
  src/system/PermissionsModule/Controller/PermissionController.php
Labels: Documentation
